//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRinfoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrivateMessage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrivateMessage()
        {
            this.PrivateMessages1 = new HashSet<PrivateMessage>();
            this.PrivateMessages11 = new HashSet<PrivateMessage>();
        }
    
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public int TopicId { get; set; }
        public string Message { get; set; }
        public System.DateTime DateTime { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> ResponseEmployeeId { get; set; }
        public Nullable<int> RequestId { get; set; }
        public Nullable<int> ResponseId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrivateMessage> PrivateMessages1 { get; set; }
        public virtual PrivateMessage PrivateMessage1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrivateMessage> PrivateMessages11 { get; set; }
        public virtual PrivateMessage PrivateMessage2 { get; set; }
        public virtual Status Status { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
