//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRinfoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkScheduleException
    {
        public int Id { get; set; }
        public int WorkScheduleId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.TimeSpan> TimeFrom { get; set; }
        public Nullable<System.TimeSpan> TimeTo { get; set; }
        public int StatusId { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual WorkSchedule WorkSchedule { get; set; }
    }
}
