//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRinfoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkTime
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan TimeFrom { get; set; }
        public System.TimeSpan TimeTo { get; set; }
        public bool WorkDay { get; set; }
        public Nullable<int> CalendarId { get; set; }
    
        public virtual Calendar Calendar { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
